### ISSUE TITLE
How to implement assignments?

### ISSUE THREAD

**Issue by cpearce31** [ga-wdi-boston/planning-genie-api#12]
I'd like to take a stab at implementing an assignment feature, but I'm unsure what the best approach is. Should it just be a foreign key reference field on materials that points to whoever it's assigned to?

Maybe it makes more sense for assignments to be a resource of their own, with references to the material, the user(s) to whom it was assigned, and who assigned it? This way we could also store the date it was assigned.

**Comment by payne-chris-r** [comment]
They're deliveries, which should be a join between users and materials. So you're exactly on the right track, but I think it's already done 😜
